# comments

FROM base-image  #To run your base image
LABEL key=value
RUN command # To run any commands inside your container
COPY src dest # To copy a host files to the container image
ADD src.tar dest # This ADD performs action like unzipping the file and put it to the destination.
WORKDIR dir # Setting work directory for the container 
ENTRYPOINT cmd 
CMD args
